version: "3.8"
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway # Using the async gateway Dockerfile
    container_name: async_posix_gateway
    restart: unless-stopped
    environment:
      - RUST_LOG=info # Optional: Adjust logging levels
    networks:
      - posix_network

  peer1:
    build:
      context: .
      dockerfile: Dockerfile.peer # Using the async peer Dockerfile
    container_name: async_posix_peer1
    restart: unless-stopped
    depends_on:
      - gateway
    environment:
      - RUST_LOG=info # Optional: Adjust logging levels
    networks:
      - posix_network

  peer2:
    build:
      context: .
      dockerfile: Dockerfile.peer # Reuse the peer Dockerfile for peer2
    container_name: async_posix_peer2
    restart: unless-stopped
    depends_on:
      - gateway
    environment:
      - RUST_LOG=info # Optional: Adjust logging levels
    networks:
      - posix_network

networks:
  posix_network:
    driver: bridge
